<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { authStore } from '$lib/stores/auth';
	import { getMemorialByCreatorUid } from '$lib/firebase/memorial';
	import { getLivestreamConfig } from '$lib/firebase/livestream';
	import type { Memorial } from '$lib/types/memorial';
	import type { LivestreamConfig } from '$lib/types/livestream';
	import { goto } from '$app/navigation';
	import { WebRTCStreamer, type StreamStats } from '$lib/services/webrtc-stream';
	import { CloudflareStreamService, type CloudflareStreamConfig } from '$lib/services/cloudflare-stream';
	
	let memorial: Memorial | null = null;
	let livestreamConfig: LivestreamConfig | null = null;
	let loading = true;
	let error = '';
	let isLive = false;
	let streamStartTime: Date | null = null;
	let elapsedTime = '00:00:00';
	let viewerCount = 0;
	let streamKey = '';
	let streamUrl = '';
	
	// WebRTC streaming variables
	let webrtcStreamer: WebRTCStreamer | null = null;
	let videoElement: HTMLVideoElement | undefined;
	let localStream: MediaStream | null = null;
	let cameraPermissionGranted = false;
	let streamingMode: 'webrtc' | 'external' = 'webrtc';
	let streamStats: StreamStats | null = null;
	let whipEndpoint = '';
	let cloudflareStreamKey = '';
	let cloudflareService: CloudflareStreamService;
	let streamConfig: CloudflareStreamConfig | null = null;

	// Check if user is an approved funeral director
	$: if ($authStore.initialized && (!$authStore.user || !$authStore.profile || 
		$authStore.profile.role !== 'FuneralDirector' || !$authStore.profile.approved)) {
		goto('/');
	}

	onMount(() => {
		if ($authStore.profile?.role === 'FuneralDirector' && $authStore.profile?.approved) {
			cloudflareService = new CloudflareStreamService();
			loadStreamingData();
			initializeWebRTCStreamer();
			
			// Update elapsed time every second when live
			const interval = setInterval(() => {
				if (isLive && streamStartTime) {
					updateElapsedTime();
				}
			}, 1000);
			
			return () => clearInterval(interval);
		}
	});

	onDestroy(() => {
		if (webrtcStreamer) {
			webrtcStreamer.destroy();
		}
		// Clean up Cloudflare Stream input when component is destroyed
		if (streamConfig && cloudflareService) {
			cloudflareService.deleteLiveInput(streamConfig.streamKey);
		}
	});

	async function loadStreamingData() {
		try {
			loading = true;
			error = '';
			
			memorial = await getMemorialByCreatorUid($authStore.user!.uid);
			
			if (memorial && memorial.customUrl) {
				livestreamConfig = await getLivestreamConfig(memorial.customUrl);
				
				// Check if payment is complete
				if (livestreamConfig?.paymentStatus !== 'paid') {
					error = 'Payment must be completed before going live. Please complete payment first.';
					return;
				}
				
				// Set up Cloudflare Stream configuration
				if (memorial.customUrl) {
					streamConfig = await cloudflareService.createLiveInput(memorial.customUrl);
					whipEndpoint = streamConfig.whipEndpoint;
					cloudflareStreamKey = streamConfig.streamKey;
					
					// Legacy RTMP for external software
					streamKey = streamConfig.streamKey;
					streamUrl = streamConfig.rtmpUrl;
				}
			} else {
				error = 'No memorial found. Please create a memorial first.';
			}
		} catch (err: any) {
			error = err.message || 'Failed to load streaming data';
			console.error('Error loading streaming data:', err);
		} finally {
			loading = false;
		}
	}

	function generateStreamKey(): string {
		// In a real implementation, this would be generated by your streaming service
		return `fd_${$authStore.user?.uid}_${Date.now()}`;
	}

	function initializeWebRTCStreamer() {
		webrtcStreamer = new WebRTCStreamer();
		
		webrtcStreamer.onStreamStart = () => {
			isLive = true;
			streamStartTime = new Date();
			console.log('WebRTC stream started');
		};
		
		webrtcStreamer.onStreamStop = () => {
			isLive = false;
			streamStartTime = null;
			elapsedTime = '00:00:00';
			localStream = null;
			console.log('WebRTC stream stopped');
		};
		
		webrtcStreamer.onError = (errorMessage: string) => {
			error = errorMessage;
			console.error('WebRTC streaming error:', errorMessage);
		};
		
		webrtcStreamer.onStatsUpdate = (stats: StreamStats) => {
			streamStats = stats;
		};
	}

	async function requestCameraAccess() {
		try {
			if (!webrtcStreamer) return;
			
			localStream = await webrtcStreamer.initializeCamera();
			cameraPermissionGranted = true;
			
			// Display camera preview
			if (videoElement && localStream) {
				videoElement.srcObject = localStream;
			}
		} catch (err) {
			console.error('Camera access error:', err);
		}
	}

	async function startWebRTCStream() {
		try {
			if (!webrtcStreamer || !localStream) {
				await requestCameraAccess();
			}
			
			if (!webrtcStreamer || !whipEndpoint || !cloudflareStreamKey) {
				error = 'Streaming configuration not ready';
				return;
			}
			
			await webrtcStreamer.startStream({
				whipEndpoint,
				streamKey: cloudflareStreamKey,
				resolution: { width: 1280, height: 720 },
				bitrate: 2500000 // 2.5 Mbps
			});
		} catch (err) {
			console.error('Failed to start WebRTC stream:', err);
		}
	}

	function stopWebRTCStream() {
		if (webrtcStreamer) {
			webrtcStreamer.stopStream();
		}
	}

	async function switchCamera() {
		if (webrtcStreamer) {
			try {
				await webrtcStreamer.switchCamera();
			} catch (err) {
				console.error('Failed to switch camera:', err);
			}
		}
	}

	// Legacy RTMP streaming functions for external software
	function startStream() {
		isLive = true;
		streamStartTime = new Date();
		console.log('Stream started:', { streamKey, streamUrl });
	}

	function stopStream() {
		isLive = false;
		streamStartTime = null;
		elapsedTime = '00:00:00';
		console.log('Stream stopped');
	}

	function updateElapsedTime() {
		if (!streamStartTime) return;
		
		const now = new Date();
		const diff = now.getTime() - streamStartTime.getTime();
		const hours = Math.floor(diff / (1000 * 60 * 60));
		const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
		const seconds = Math.floor((diff % (1000 * 60)) / 1000);
		
		elapsedTime = `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
	}

	function copyStreamKey() {
		navigator.clipboard.writeText(streamKey);
		// You could add a toast notification here
	}

	function copyStreamUrl() {
		navigator.clipboard.writeText(streamUrl);
		// You could add a toast notification here
	}

	function formatDate(dateStr: string | null): string {
		if (!dateStr) return 'Not specified';
		try {
			return new Date(dateStr).toLocaleDateString('en-US', {
				weekday: 'long',
				year: 'numeric',
				month: 'long',
				day: 'numeric'
			});
		} catch {
			return dateStr;
		}
	}

	function formatTime(timeStr: string | null): string {
		if (!timeStr) return 'Not specified';
		try {
			const [hours, minutes] = timeStr.split(':');
			const date = new Date();
			date.setHours(parseInt(hours), parseInt(minutes));
			return date.toLocaleTimeString('en-US', {
				hour: 'numeric',
				minute: '2-digit',
				hour12: true
			});
		} catch {
			return timeStr;
		}
	}
</script>

<svelte:head>
	<title>Livestreaming - TributeStream</title>
	<meta name="description" content="Funeral director livestreaming interface" />
</svelte:head>

{#if loading}
	<div class="flex items-center justify-center py-12">
		<div class="text-center">
			<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500 mx-auto mb-4"></div>
			<p class="text-secondary">Loading streaming interface...</p>
		</div>
	</div>
{:else if error}
	<div class="container mx-auto px-4 py-8">
		<div class="max-w-md mx-auto">
			<aside class="alert variant-filled-error">
				<div class="alert-message">
					<h3 class="h3">Error</h3>
					<p>{error}</p>
				</div>
			</aside>
			<div class="text-center mt-6">
				<a href="/schedule" class="btn variant-filled-primary">Back to Dashboard</a>
			</div>
		</div>
	</div>
{:else if memorial && livestreamConfig}
	<div class="container mx-auto px-4 py-8">
		<div class="max-w-6xl mx-auto">
			<!-- Header -->
			<div class="flex items-center justify-between mb-8">
				<div>
					<h1 class="h1">Livestreaming</h1>
					<p class="text-secondary">Memorial service for {memorial.lovedOneName}</p>
				</div>
				<div class="flex items-center space-x-4">
					<div class="flex items-center space-x-2">
						<div class="w-3 h-3 rounded-full {isLive ? 'bg-red-500 animate-pulse' : 'bg-gray-400'}"></div>
						<span class="font-semibold {isLive ? 'text-red-500' : 'text-gray-500'}">
							{isLive ? 'LIVE' : 'OFFLINE'}
						</span>
					</div>
					{#if isLive}
						<span class="badge variant-filled-surface">{elapsedTime}</span>
					{/if}
				</div>
			</div>

			<div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
				<!-- Main Streaming Controls -->
				<div class="lg:col-span-2 space-y-6">
					<!-- Camera Preview -->
					<div class="card p-6">
						<h2 class="h2 mb-4">Camera Preview</h2>
						<div class="relative bg-black rounded-lg overflow-hidden aspect-video">
							{#if localStream}
								<video 
									bind:this={videoElement}
									autoplay 
									muted 
									playsinline
									class="w-full h-full object-cover"
								></video>
								<div class="absolute top-4 right-4 flex space-x-2">
									<button 
										class="btn variant-filled-surface btn-sm"
										on:click={switchCamera}
										title="Switch Camera"
									>
										🔄
									</button>
								</div>
							{:else}
								<div class="flex items-center justify-center h-full text-white">
									<div class="text-center">
										<div class="text-6xl mb-4">📹</div>
										<p class="text-lg mb-4">Camera Preview</p>
										{#if !cameraPermissionGranted}
											<button 
												class="btn variant-filled-primary"
												on:click={requestCameraAccess}
											>
												Enable Camera
											</button>
										{/if}
									</div>
								</div>
							{/if}
						</div>
					</div>

					<!-- Stream Status Card -->
					<div class="card p-6">
						<h2 class="h2 mb-4">Stream Status</h2>
						<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
							<div class="text-center">
								<div class="text-2xl mb-1">{isLive ? '🔴' : '⚫'}</div>
								<div class="text-sm font-semibold">{isLive ? 'Live' : 'Offline'}</div>
							</div>
							<div class="text-center">
								<div class="text-2xl mb-1">👥</div>
								<div class="text-sm font-semibold">{viewerCount} Viewers</div>
							</div>
							<div class="text-center">
								<div class="text-2xl mb-1">⏱️</div>
								<div class="text-sm font-semibold">{elapsedTime}</div>
							</div>
							<div class="text-center">
								<div class="text-2xl mb-1">📺</div>
								<div class="text-sm font-semibold">
									{streamStats ? `${streamStats.resolution.width}x${streamStats.resolution.height}` : 'HD Quality'}
								</div>
							</div>
						</div>
						
						{#if streamStats}
							<div class="mt-4 pt-4 border-t border-surface-300 dark:border-surface-600">
								<div class="grid grid-cols-3 gap-4 text-sm">
									<div class="text-center">
										<div class="font-semibold">{Math.round(streamStats.framesPerSecond)} FPS</div>
										<div class="text-xs text-secondary">Frame Rate</div>
									</div>
									<div class="text-center">
										<div class="font-semibold">{Math.round(streamStats.bytesPerSecond / 1024)} KB/s</div>
										<div class="text-xs text-secondary">Bitrate</div>
									</div>
									<div class="text-center">
										<div class="font-semibold">{streamStats.isConnected ? '🟢' : '🔴'}</div>
										<div class="text-xs text-secondary">Connection</div>
									</div>
								</div>
							</div>
						{/if}
					</div>

					<!-- Stream Controls -->
					<div class="card p-6">
						<h2 class="h2 mb-4">Stream Controls</h2>
						
						<!-- Streaming Mode Toggle -->
						<div class="mb-4">
							<div class="flex items-center justify-center space-x-4">
								<button 
									class="btn {streamingMode === 'webrtc' ? 'variant-filled-primary' : 'variant-ghost-surface'}"
									on:click={() => streamingMode = 'webrtc'}
								>
									📹 Browser Camera
								</button>
								<button 
									class="btn {streamingMode === 'external' ? 'variant-filled-primary' : 'variant-ghost-surface'}"
									on:click={() => streamingMode = 'external'}
								>
									💻 External Software
								</button>
							</div>
						</div>

						{#if streamingMode === 'webrtc'}
							<!-- WebRTC Controls -->
							<div class="flex justify-center space-x-4">
								{#if !cameraPermissionGranted}
									<button 
										class="btn variant-filled-primary text-lg px-8 py-3"
										on:click={requestCameraAccess}
									>
										<span>📹</span>
										<span>Enable Camera</span>
									</button>
								{:else if !isLive}
									<button 
										class="btn variant-filled-success text-lg px-8 py-3"
										on:click={startWebRTCStream}
									>
										<span>🔴</span>
										<span>Go Live</span>
									</button>
								{:else}
									<button 
										class="btn variant-filled-error text-lg px-8 py-3"
										on:click={stopWebRTCStream}
									>
										<span>⏹️</span>
										<span>Stop Stream</span>
									</button>
								{/if}
							</div>
						{:else}
							<!-- External Software Controls -->
							<div class="flex justify-center space-x-4">
								{#if !isLive}
									<button 
										class="btn variant-filled-success text-lg px-8 py-3"
										on:click={startStream}
									>
										<span>📹</span>
										<span>Start Stream</span>
									</button>
								{:else}
									<button 
										class="btn variant-filled-error text-lg px-8 py-3"
										on:click={stopStream}
									>
										<span>⏹️</span>
										<span>Stop Stream</span>
									</button>
								{/if}
							</div>
						{/if}
					</div>

					<!-- Stream Configuration -->
					<div class="card p-6">
						<h2 class="h2 mb-4">Stream Configuration</h2>
						<div class="space-y-4">
							<div>
								<label class="label mb-2">
									<span class="font-semibold">Stream URL</span>
								</label>
								<div class="flex items-center space-x-2">
									<input 
										type="text" 
										value={streamUrl} 
										readonly 
										class="input flex-1 bg-surface-100 dark:bg-surface-800"
									/>
									<button 
										class="btn variant-filled-secondary"
										on:click={copyStreamUrl}
									>
										Copy
									</button>
								</div>
							</div>
							<div>
								<label class="label mb-2">
									<span class="font-semibold">Stream Key</span>
								</label>
								<div class="flex items-center space-x-2">
									<input 
										type="password" 
										value={streamKey} 
										readonly 
										class="input flex-1 bg-surface-100 dark:bg-surface-800"
									/>
									<button 
										class="btn variant-filled-secondary"
										on:click={copyStreamKey}
									>
										Copy
									</button>
								</div>
							</div>
						</div>
						
						<div class="alert variant-ghost-primary mt-4">
							<div class="alert-message">
								<h3 class="h4">📋 Setup Instructions</h3>
								<ol class="list-decimal list-inside space-y-1 text-sm mt-2">
									<li>Copy the Stream URL and Stream Key above</li>
									<li>Open your streaming software (OBS, XSplit, etc.)</li>
									<li>Add the Stream URL and Key to your streaming settings</li>
									<li>Configure your camera and audio sources</li>
									<li>Click "Start Stream" when ready to go live</li>
								</ol>
							</div>
						</div>
					</div>
				</div>

				<!-- Sidebar -->
				<div class="space-y-6">
					<!-- Service Details -->
					<div class="card p-6">
						<h3 class="h3 mb-4">Service Details</h3>
						<div class="space-y-3 text-sm">
							<div>
								<span class="font-semibold">Date:</span>
								<div class="mt-1">
									{livestreamConfig.formData.mainService.time.isUnknown 
										? 'Date to be determined' 
										: formatDate(livestreamConfig.formData.mainService.time.date)}
								</div>
							</div>
							<div>
								<span class="font-semibold">Time:</span>
								<div class="mt-1">
									{livestreamConfig.formData.mainService.time.isUnknown 
										? 'Time to be determined' 
										: formatTime(livestreamConfig.formData.mainService.time.time)}
								</div>
							</div>
							<div>
								<span class="font-semibold">Location:</span>
								<div class="mt-1">
									{livestreamConfig.formData.mainService.location.isUnknown 
										? 'Location to be determined' 
										: `${livestreamConfig.formData.mainService.location.name}`}
								</div>
							</div>
						</div>
					</div>

					<!-- Memorial Link -->
					<div class="card p-6">
						<h3 class="h3 mb-4">Memorial Page</h3>
						<p class="text-sm text-secondary mb-4">Share this link with family and friends:</p>
						<div class="flex items-center space-x-2">
							<input 
								type="text" 
								value="https://tributestream.com/{memorial.customUrl}" 
								readonly 
								class="input flex-1 text-xs bg-surface-100 dark:bg-surface-800"
							/>
							<button 
								class="btn variant-filled-secondary btn-sm"
								on:click={() => navigator.clipboard.writeText(`https://tributestream.com/${memorial.customUrl}`)}
							>
								Copy
							</button>
						</div>
						<a 
							href="/{memorial.customUrl}" 
							target="_blank" 
							class="btn variant-filled-primary w-full mt-3"
						>
							View Memorial Page
						</a>
					</div>

					<!-- Quick Actions -->
					<div class="card p-6">
						<h3 class="h3 mb-4">Quick Actions</h3>
						<div class="space-y-2">
							<a href="/schedule" class="btn variant-filled-secondary w-full">
								Back to Dashboard
							</a>
							<button class="btn variant-ghost-surface w-full">
								Test Stream
							</button>
							<button class="btn variant-ghost-surface w-full">
								Technical Support
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{:else}
	<div class="container mx-auto px-4 py-8 text-center">
		<h1 class="h1 mb-4">No Memorial Found</h1>
		<p class="text-secondary mb-6">Please create a memorial and complete payment before accessing the livestreaming interface.</p>
		<a href="/schedule" class="btn variant-filled-primary">Go to Dashboard</a>
	</div>
{/if}
